name: Bug report
description: Report a problem with K1C-Board
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Steps to reproduce
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Commit/Version
  - type: textarea
    id: logs
    attributes:
      label: Logs or ERC/DRC excerpts