name: Feature request
description: Propose an enhancement
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal